blank_issues_enabled: true
contact_links:
  - name: General Question
    url: https://github.com/aksharap22/LifeOS/discussions
    about: For general questions that aren't a bug, feature request, or doc/setup issue
